# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170429_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='particle',
        ),
        migrations.AlterField(
            model_name='jobindexpagejob',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ParticleSnippet',
        ),
    ]
