# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('core', '0003_auto_20170425_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobindexpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
