# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170429_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespageservice',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
