# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('core', '0004_auto_20170429_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespageservice',
            name='svg',
        ),
        migrations.AddField(
            model_name='servicespageservice',
            name='service_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
