# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobindexpage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobindexpage',
            name='main_image',
        ),
    ]
