# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('core', '0007_auto_20170429_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='standardpageclient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='standardpageclient',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='standardpageclient',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='standardpageclient',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagecontentblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='StandardPage',
        ),
        migrations.DeleteModel(
            name='StandardPageClient',
        ),
        migrations.DeleteModel(
            name='StandardPageContentBlock',
        ),
        migrations.DeleteModel(
            name='StandardPageRelatedLink',
        ),
    ]
