# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('core', '0008_auto_20170429_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupformpage',
            name='call_to_action_image',
        ),
        migrations.RemoveField(
            model_name='signupformpage',
            name='email_attachment',
        ),
        migrations.RemoveField(
            model_name='signupformpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='signupformpagebullet',
            name='page',
        ),
        migrations.RemoveField(
            model_name='signupformpagelogo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='signupformpagelogo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='signupformpagequote',
            name='page',
        ),
        migrations.DeleteModel(
            name='SignUpFormPageResponse',
        ),
        migrations.DeleteModel(
            name='SignUpFormPage',
        ),
        migrations.DeleteModel(
            name='SignUpFormPageBullet',
        ),
        migrations.DeleteModel(
            name='SignUpFormPageLogo',
        ),
        migrations.DeleteModel(
            name='SignUpFormPageQuote',
        ),
    ]
